name: Docker Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: dipak2515
        password: Omsai@9552

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .github/workflows
        push: true
        tags: dipak2515/ubuntu562023:latest
